### ISSUE TITLE
Web Console Commands 

### ISSUE THREAD

**Issue by HDVinnie** [Swizards/QuickBox#41]
Console commands like set disk are not working?

**Comment by JMSDOnline** [comment]
I would need more details in order to find resolution on this.

When you type in SSH as root or the master sudoer (installer of the script) what is returned when you type in ``setdisk`` 

There have been no other reports in regards to this type of issue, so any additional evidence you can provide will be greatly appreciated.

**Comment by HDVinnie** [comment]
I log into quickbox GUI using the main sudden account. Click Web Console. type username and pass of sudoer. says authenticated. type setdisk and say command not found. or if I SSH first then setdisk. I get following error:

/etc/ssh/ssh_config: line 55: Bad configuration option: permitrootlogin
/etc/ssh/ssh_config: terminating, 1 bad configuration options

Im sure I'm doing it wrong. but i need to do it on main account so this show correctly right?

http://i.imgur.com/V7efiv5.png?1

**Comment by JMSDOnline** [comment]
The GUI Web Console is not to be substituted for master commands. You will need to login via SSH as root in order to run the administrator commands. The GUI Web Console is for a limited set of commands, i.e; creating directories, unzipping archives..etc.

You can login to ssh via your server ip on port 4747

**Comment by HDVinnie** [comment]
ok opened terminal on my MAC. ran following ssh username@IP -p4747
it connected fine
typed setdisk
command not found?

**Comment by HDVinnie** [comment]
I figured it out...thanks for the assistance. I feel dumb.

**Comment by JMSDOnline** [comment]
Glad you got it sorted @HDVinnie. :smile_cat:
